### ISSUE TITLE
ubuntu: switch to a LTS release

### ISSUE THREAD

**Issue by unclejack** [contiv/build#46]
We're on Ubuntu 15.04 right now and that's an issue. Support is no longer provided for Ubuntu 15.04 and there's no point in tracking the latest unstable.

Perhaps we should switch to 14.04.

**Comment by sheerun** [comment]
Do you still support only 15.04, or 16.04 LTS as well?

**Comment by unclejack** [comment]
@sheerun Ubuntu 15.04 is deprecated. It's not supported any more. It's not supported by Canonical and it's not supported by anyone else either. My PR removes it from this repository.

I'll close this issue now because the Ubuntu box is using Ubuntu 16.04.
